### PR TITLE
fixed YoutubePlaylist spec

### PR DESCRIPTION
**Pull request by vheuken**
Turns out, the playlist being tested against has had a video added recently. This caused a spec to fail.

I added the new video to the spec and it works now.

### CODE REVIEW

**Comment by thibaudgg** [comment]
It's still failing for me (rebased on master) with with a lot of 404. Could you try to rebase this PR on master? Thanks!

```
  1) VideoInfo::Providers::YoutubePlaylist#available? with valid playlist #available? should be truthy
     Failure/Error: it { is_expected.to be_truthy }
       expected: truthy value
            got: false
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:30:in `block (5 levels) in <top (required)>'

  2) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #title 
     Failure/Error: subject { super().title }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtube.rb:93:in `_video_snippet'
     # ./lib/video_info/providers/youtube.rb:18:in `title'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:83:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:84:in `block (4 levels) in <top (required)>'

  3) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #description 
     Failure/Error: subject { super().description }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtubeplaylist.rb:32:in `_playlist_entry'
     # ./lib/video_info/providers/youtubeplaylist.rb:22:in `description'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:88:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:89:in `block (4 levels) in <top (required)>'

  4) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #thumbnail_small 
     Failure/Error: subject { super().thumbnail_small }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtube.rb:93:in `_video_snippet'
     # ./lib/video_info/providers/youtube.rb:47:in `thumbnail_small'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:118:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:119:in `block (4 levels) in <top (required)>'

  5) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #thumbnail_medium 
     Failure/Error: subject { super().thumbnail_medium }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtube.rb:93:in `_video_snippet'
     # ./lib/video_info/providers/youtube.rb:51:in `thumbnail_medium'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:123:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:124:in `block (4 levels) in <top (required)>'

  6) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #thumbnail_large 
     Failure/Error: subject { super().thumbnail_large }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtube.rb:93:in `_video_snippet'
     # ./lib/video_info/providers/youtube.rb:55:in `thumbnail_large'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:128:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:129:in `block (4 levels) in <top (required)>'

  7) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #videos 
     Failure/Error: subject { super().videos }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtubeplaylist.rb:32:in `_playlist_entry'
     # ./lib/video_info/providers/youtubeplaylist.rb:48:in `_playlist_video_ids'
     # ./lib/video_info/providers/youtubeplaylist.rb:12:in `videos'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:133:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:134:in `block (4 levels) in <top (required)>'

  8) VideoInfo::Providers::YoutubePlaylist with playlist PL0E8117603D70E10A in embed path #videos 
     Failure/Error: subject { super().videos }
     OpenURI::HTTPError:
       404 Not Found
     # ./lib/video_info/provider.rb:60:in `_set_data_from_api'
     # ./lib/video_info/provider.rb:32:in `data'
     # ./lib/video_info/providers/youtubeplaylist.rb:32:in `_playlist_entry'
     # ./lib/video_info/providers/youtubeplaylist.rb:48:in `_playlist_video_ids'
     # ./lib/video_info/providers/youtubeplaylist.rb:12:in `videos'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:152:in `block (4 levels) in <top (required)>'
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:153:in `block (4 levels) in <top (required)>'
```

**Comment by vheuken** [comment]
Odd. I just tried it and it only fails when I rebase with master.

**Comment by vheuken** [comment]
Oh, I see the problem. It uses the V2 API still but it inherits _api_base and _api_url from Youtube, which uses the V3 API. Simply switching the _api_url and _api_base to the V2 version causes some other stuff to break.

I suppose I need to just switch it to the V3 API. I'll do that either tonight or tomorrow.

**Comment by thibaudgg** [comment]
@vheuken awesome thanks!

**Comment by vheuken** [comment]
I'm down to only three specs failing. Getting there...

**Comment by thibaudgg** [comment]
:+1:

**Comment by vheuken** [comment]
Down to two (also an ugly hack that'll be removed). I'll hopefully get to
them today.

**Comment by vheuken** [comment]
Hm....this is odd. The API seems to only be returning 5 videos on a playlist that has 6. Wonder what the issue is.

Only one remaining failing spec, though!

**Comment by vheuken** [comment]
Whelp, looks like there is a bug in the Youtube PlaylistsItems API where some videos just don't show up. That's annoying. 

Other people who hit the bug:
http://stackoverflow.com/questions/22605693/youtube-api-v3-missing-items-in-playlist-when-requesting-them-with-playlistite
http://stackoverflow.com/questions/22499170/retrieve-youtube-playlist-wrong-when-playlist-items-count-over-100/22499606?noredirect=1#comment34231492_22499606

**Comment by thibaudgg** [comment]
@vheuken do you think micro format would help for Youtube Playlists as well?

**Comment by vheuken** [comment]
There is, but only for playlist description, title, and keywords.

**Comment by thibaudgg** [comment]
@vheuken ok, then it would be nice to support them. What do you think?

**Comment by vheuken** [comment]
@thibaudgg Sure, I can do that. Just throw an error saying that you need to provide an API key to access the stuff that requires the API?

**Comment by thibaudgg** [comment]
Perfect!

**Comment by vheuken** [comment]
All that is left is fixing `#available`...

**Comment by thibaudgg** [comment]
you're almost done, go! :+1:

**Comment by vheuken** [comment]
Done! I added two dependencies: Nokogiri for HTML parsing and open_uri_redirections because open-uri doesn't handle http => https redirections. 

Once this is merged I'll finish up Youtube, which should be less work since I think the functions here can just be moved over to Youtube.

**Comment by vheuken** [comment]
Oh wait, lots of houndci warnings. I'll look through them.

**Comment by thibaudgg** [comment]
I would prefer [Oga](https://github.com/YorickPeterse/oga) over Nokogiri so we don't add any dependencies on libxml.

**Comment by vheuken** [comment]
@thibaudgg Sure, I can switch it.

**Comment by vheuken** [comment]
Ported to Oga. Way faster than I expected. Now for the houndci violations!

**Comment by thibaudgg** [comment]
:+1:

**Comment by vheuken** [comment]
I fixed the prefer "`.detect` over `.find`" violation and a tab violation. Everything else seems to be either long strings or stuff from the "new" spec (I just made a copy of the API spec and got rid of the `before(:all)`". I think that's it.

**Comment by thibaudgg** [comment]
Great, let wait travis-ci result then.

**Comment by vheuken** [comment]
Sorry about the tab commits. Reformatted and lost my .vimrc so vim wasn't handling that for me.....

**Comment by thibaudgg** [comment]
:dancers:

**Comment by vheuken** [comment]
Not sure what is up with the Vkontakte stuff under JRuby in Travis. It's fine on my machine and appears to have randomly showed up when PR #76 got merged (I assume it was a coincidence)

**Comment by thibaudgg** [comment]
@vheuken only `rspec ./spec/lib/video_info/providers/youtube_playlist_api_spec.rb:137` seems to fail on travis now, right?

**Comment by vheuken** [comment]
I mentioned in an earlier comment on this PR that that was due to a bug in the Youtube API (as far as I can tell). For some playlists, it seems to be missing videos.

Unfortunately, we can't really get the videos via page scraping, so the API is our only option. This is annoying, but there is nothing we can really do about it except maybe complain to Youtube/Google.

**Comment by thibaudgg** [comment]
Should we not update the spec to be more permissive then, or maybe remove it completely? It would be nice to have all specs passing on master :smile:

**Comment by vheuken** [comment]
I actually looked around for a way to mark a spec as expected to fail when I first noticed the issue. 

...I guess I didn't look hard enough : ^ )

I marked it as `pending`, so it should now just throw a _warning_ instead of an error.

**Comment by vheuken** [comment]
Not sure why 1.9.3 is stalling on Travis. It appears to be doing so on the Vkontakte specs. Stra

**Comment by thibaudgg** [comment]
Yes we could remove 1.9.3 support IMHO and go >= 2.2.2 only :)

**Comment by vheuken** [comment]
Actually, I'm pretty sure this _must_ be a network issue on either Travis's or Vkontakte's end. The only one that passed the latest Travis was 2.1, but in the previous one only 2.0 passed. 1.9.3's only failure is a timeout and the rest just stall. That might be the issue with JRuby, too. 

Maybe we should just merge this and see what happens when I fix Youtube?

**Comment by thibaudgg** [comment]
:+1:

**Pull request merged**
