### PR TITLE
Add support for embedding rutube videos

### PR DESCRIPTION
**Pull request by drakmail**
Sometimes vkontakte video is just embedded video from rutube.ru %)

### CODE REVIEW

**Comment by drakmail** [comment]
PS. Youtube Playlists failed :disappointed:

**Comment by thibaudgg** [comment]
Mmm too bad, any ideas why?

**Comment by drakmail** [comment]
I absolutely have no ideas =/ I'm have this in master branch too.

**Comment by drakmail** [comment]
```
test|⇒ git clone git@github.com:thibaudgg/video_info.git
Cloning into 'video_info'...
remote: Counting objects: 3382, done.
remote: Total 3382 (delta 0), reused 0 (delta 0), pack-reused 3382
Receiving objects: 100% (3382/3382), 1.46 MiB | 284.00 KiB/s, done.
Resolving deltas: 100% (1275/1275), done.
Checking connectivity... done.
test|⇒ cd video_info
video_info|master ⇒ rspec spec/lib/video_info/providers/youtube_playlist_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
....................F....

Failures:

  1) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #videos should contain exactly #<VideoInfo:0x007fa11ba53908 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba52530 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=_Bt3-WsHfB0", @video_id="_Bt3-WsHfB0">>, #<VideoInfo:0x007fa11ba51ec8 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba4bf78 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=9g2U12SsRns", @video_id="9g2U12SsRns">>, #<VideoInfo:0x007fa11ba4b4b0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba48800 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=8b0aEoxqqC0", @video_id="8b0aEoxqqC0">>, #<VideoInfo:0x007fa11ba3fbb0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba3cc58 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=6c3mHikRz0I", @video_id="6c3mHikRz0I">>, and #<VideoInfo:0x007fa11ba3bec0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba23820 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=OQVHWsTHcoc", @video_id="OQVHWsTHcoc">>
     Failure/Error: it { is_expected.to match_array(videos) }
       expected collection contained:  [#<VideoInfo:0x007fa11ba53908 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba52530 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=_Bt3-WsHfB0", @video_id="_Bt3-WsHfB0">>, #<VideoInfo:0x007fa11ba51ec8 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba4bf78 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=9g2U12SsRns", @video_id="9g2U12SsRns">>, #<VideoInfo:0x007fa11ba4b4b0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba48800 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=8b0aEoxqqC0", @video_id="8b0aEoxqqC0">>, #<VideoInfo:0x007fa11ba3fbb0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba3cc58 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=6c3mHikRz0I", @video_id="6c3mHikRz0I">>, #<VideoInfo:0x007fa11ba3bec0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba23820 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=OQVHWsTHcoc", @video_id="OQVHWsTHcoc">>]
       actual collection contained:    [#<VideoInfo:0x007fa11ba78ed8 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba731e0 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=Oi67QjrXy2w", @video_id="Oi67QjrXy2w">>, #<VideoInfo:0x007fa11ba72bc8 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba71138 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=OQVHWsTHcoc", @video_id="OQVHWsTHcoc">>, #<VideoInfo:0x007fa11ba70b98 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba6b710 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=_Bt3-WsHfB0", @video_id="_Bt3-WsHfB0">>, #<VideoInfo:0x007fa11ba6b148 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba689c0 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=9g2U12SsRns", @video_id="9g2U12SsRns">>, #<VideoInfo:0x007fa11ba5bcc0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba59ee8 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=6c3mHikRz0I", @video_id="6c3mHikRz0I">>, #<VideoInfo:0x007fa11ba59358 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba53e30 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=8b0aEoxqqC0", @video_id="8b0aEoxqqC0">>]
       the extra elements were:        [#<VideoInfo:0x007fa11ba78ed8 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba731e0 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=Oi67QjrXy2w", @video_id="Oi67QjrXy2w">>]
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:133:in `block (4 levels) in <top (required)>'

Finished in 2.81 seconds (files took 3.35 seconds to load)
25 examples, 1 failure

Failed examples:

rspec ./spec/lib/video_info/providers/youtube_playlist_spec.rb:133 # VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #videos should contain exactly #<VideoInfo:0x007fa11ba53908 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba52530 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=_Bt3-WsHfB0", @video_id="_Bt3-WsHfB0">>, #<VideoInfo:0x007fa11ba51ec8 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba4bf78 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=9g2U12SsRns", @video_id="9g2U12SsRns">>, #<VideoInfo:0x007fa11ba4b4b0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba48800 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=8b0aEoxqqC0", @video_id="8b0aEoxqqC0">>, #<VideoInfo:0x007fa11ba3fbb0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba3cc58 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=6c3mHikRz0I", @video_id="6c3mHikRz0I">>, and #<VideoInfo:0x007fa11ba3bec0 @provider=#<VideoInfo::Providers::Youtube:0x007fa11ba23820 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=OQVHWsTHcoc", @video_id="OQVHWsTHcoc">>

video_info|master⚡ ⇒
```

**Comment by thibaudgg** [comment]
Ok master should be fixed once #66 has been resolved. I'll ping you when you'll be able to rebase on master. Thanks!

**Comment by drakmail** [comment]
Awesome, thank you!

**Comment by thibaudgg** [comment]
Master should be back to green now, could you rebase please? Thanks!

**Comment by vheuken** [comment]
@drakmail I went ahead and rebased this for you. It is in @thibaudgg's repository under the branch embed-rubtube

**Comment by vheuken** [comment]
It looks like 3 specs fail:

```
Failures:

  1) VideoInfo::Providers::Vkontakte with video http://vk.com/video53128560_168563219 title 
     Failure/Error: its(:title)            { should eq 'Настя Юрасова/ Стрип-пластика/ Jakwob feat. Maiday - Fade' }
     NoMethodError:
       undefined method `gsub' for nil:NilClass
     # ./lib/video_info/providers/vkontakte.rb:45:in `title'
     # ./spec/lib/video_info/providers/vkontakte_spec.rb:86:in `block (3 levels) in <top (required)>'

  2) VideoInfo::Providers::Vkontakte with video http://vk.com/video53128560_168563219 embed_url should eq "//rutube.ru/video/embed/6964152?vk_puid23=&vk_puid24=&vk_puid34=0"
     Failure/Error: its(:embed_url)        { should eq '//rutube.ru/video/embed/6964152?vk_puid23=&vk_puid24=&vk_puid34=0' }
       
       expected: "//rutube.ru/video/embed/6964152?vk_puid23=&vk_puid24=&vk_puid34=0"
            got: "//vk.com/video_ext.php?oid=53128560&id=168563219&hash="
       
       (compared using ==)
     # ./spec/lib/video_info/providers/vkontakte_spec.rb:87:in `block (3 levels) in <top (required)>'

  3) VideoInfo::Providers::Vkontakte with video http://vk.com/video53128560_168563219 embed_code should eq "<iframe src=\"//rutube.ru/video/embed/6964152?vk_puid23=&vk_puid24=&vk_puid34=0\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe>"
     Failure/Error: its(:embed_code)       { should eq '<iframe src="//rutube.ru/video/embed/6964152?vk_puid23=&vk_puid24=&vk_puid34=0" frameborder="0" allowfullscreen="allowfullscreen"></iframe>' }
       
       expected: "<iframe src=\"//rutube.ru/video/embed/6964152?vk_puid23=&vk_puid24=&vk_puid34=0\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe>"
            got: "<iframe src=\"//vk.com/video_ext.php?oid=53128560&id=168563219&hash=\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe>"
       
       (compared using ==)
     # ./spec/lib/video_info/providers/vkontakte_spec.rb:88:in `block (3 levels) in <top (required)>'

Finished in 1 minute 5.91 seconds (files took 0.31131 seconds to load)
368 examples, 3 failures, 1 pending
```

**Comment by 0mega** [comment]
I don't know if it's the case here, but for me some specs fail in master because of locale.
I am running tests from Portugal and so the video titles from Youtube does not match for me, because the expected title is in English and the actual title I receive is in Portuguese =P.

I was looking at those to try to fix them, but it's best to fix this ones first.

So where do I start? The most recent code of this PR is in embed-rubtube?

**Comment by vheuken** [comment]
>So where do I start? The most recent code of this PR is in embed-rubtube?

Yes, that code should be rebased with master (you'd might want to rebase it again, considering some changes have occurred since then)

**Comment by vheuken** [comment]
>I don't know if it's the case here, but for me some specs fail in master because of locale.
I am running tests from Portugal and so the video titles from Youtube does not match for me, because the expected title is in English and the actual title I receive is in Portuguese =P.

Can you open up a new issue for that? Thanks.

**Comment by 0mega** [comment]
For some reason my errors are completely different from yours (ignoring the ones originated by locale)

```
Failures:

  1) VideoInfo::Providers::Vimeo#available? with 'this video does not exist' video #available? should not be available
     Failure/Error: it { is_expected.to_not be_available }
       expected `#<VideoInfo:0x007fe3e18c22c0 @provider=#<VideoInfo::Providers::Vimeo:0x007fe3e18c1c08 @options={"User-Agent"=>"VideoInfo/2.4.2", "Authorization"=>"bearer 6b66b015a3504793b4f541d878f46ff6", "Accept"=>"application/vnd.vimeo.*+json;version=3.2"}, @url="http://vimeo.com/59312311", @video_id="59312311">>.available?` to return false, got true
     # ./spec/lib/video_info/providers/vimeo_spec.rb:55:in `block (5 levels) in <top (required)>'

  2) VideoInfo::Providers::Vimeo#available? with 'password required' video #available? should not be available
     Failure/Error: it { is_expected.to_not be_available }
       expected `#<VideoInfo:0x007fe3e18e53d8 @provider=#<VideoInfo::Providers::Vimeo:0x007fe3e18e4d20 @options={"User-Agent"=>"VideoInfo/2.4.2", "Authorization"=>"bearer 6b66b015a3504793b4f541d878f46ff6", "Accept"=>"application/vnd.vimeo.*+json;version=3.2"}, @url="http://vimeo.com/74636562", @video_id="74636562">>.available?` to return false, got true
     # ./spec/lib/video_info/providers/vimeo_spec.rb:63:in `block (5 levels) in <top (required)>'

  3) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #title should eq "YouTube Policy and Copyright"
     Failure/Error: it { is_expected.to eq 'YouTube Policy and Copyright' }
       
       expected: "YouTube Policy and Copyright"
            got: "Política do YouTube e direitos de autor"
       
       (compared using ==)
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:87:in `block (4 levels) in <top (required)>'

  4) VideoInfo::Providers::YoutubePlaylist with playlist PL9hW1uS6HUftLdHI6RIsaf #description should eq "Learn more about copyright basics, flagging, and the YouTube community."
     Failure/Error: it { is_expected.to eq 'Learn more about copyright basics, flagging, and the YouTube community.' }
       
       expected: "Learn more about copyright basics, flagging, and the YouTube community."
            got: "Saiba mais acerca das noções básicas de direitos de autor, das denúncias e da comunidade YouTube."
       
       (compared using ==)
     # ./spec/lib/video_info/providers/youtube_playlist_spec.rb:92:in `block (4 levels) in <top (required)>'

  5) VideoInfo::Providers::Youtube with video mZqGqE0D0n4 #view_count should be > 4000
     Failure/Error: it { is_expected.to be > 4000 }
       expected: > 4000
            got:   6
     # ./spec/lib/video_info/providers/youtube_spec.rb:207:in `block (4 levels) in <top (required)>'

Finished in 5.16 seconds (files took 0.57073 seconds to load)
362 examples, 5 failures, 1 pending
```

**Comment by vheuken** [comment]
@0mega Those Vimeo issues were fixed in master _after_ I rebased this. You should rebase with master again.

**Comment by 0mega** [comment]
I guess after #106 no specs are failing so this PR can be closed

**Comment by thibaudgg** [comment]
Could you rebase it on master, so we're sure that everything is green? Thanks!

**Comment by 0mega** [comment]
I guess I made a mistake. The PR #106 you just merged, is actually the embed_rutube branch rebased on master. The embed_rutube branch was derived from this PR so I guess my PR #106 is exactly what you are asking for. Maybe I should have made the PR to the embed_rutube branch instead of master.

**Comment by vheuken** [comment]
@0mega Are you sure? Looking at #106 I only see your change, not @drakmail's.

**Comment by 0mega** [comment]
@vheuken Not completely, no.

When I read this comment:
> @drakmail I went ahead and rebased this for you. It is in @thibaudgg's repository under the branch embed-rubtube

I understood that you had created a branch with this implementation and rebased it on master. So in my head I was working with all @drakmail changes, but it looks like I was wrong.

So should I start a branch off of `drakmail:master` and rebase it on `thibaudgg:master`?

**Comment by vheuken** [comment]
@0mega Yeah, try that. I think I might have screwed up the rebase (Whoops!!)

**Comment by vheuken** [comment]
@drakmail Your change was merged in with #108. Thanks!

**Pull request closed without merging**
