### PR TITLE
Add safe navigation for user_interaction_count

### LINKED ISSUE #225: Vimeo Scraper: interactionStatistic can be missing
Here is an example of a video that does not have `interactionStatistic` in the application/ld+json `<script>` tag.

https://vimeo.com/7848846

It causes the following error:

```
NoMethodError: undefined method `find' for nil:NilClass

        interaction_statistic.find do |stat|
                             ^^^^^
```

### PR DESCRIPTION
**Pull request by Spone**
Close #225

### CODE REVIEW

**Comment by markets** [comment]
Hey @Spone 👋🏼 

Yeah! The specs for this project are a bit hard to maintain. For example, for YouTube and Vimeo, we have 2 "versions" for each service: scraper or API.

I've fixed some stuff, mainly related to specs+VCR, here 👉🏼 #227. Could you please update your branch? 

To fully run the specs locally, you need a couple of ENV vars in your machine (the ones related to Youtube and Vimeo apis). You can create those keys by yourself ([docs](https://github.com/thibaudgg/video_info?tab=readme-ov-file#note-for-youtube-and-vimeo-usage)), but I can also share with you the ones we are using for dev/testing. The CI already [uses them](https://github.com/thibaudgg/video_info/blob/master/.github/workflows/ci.yml#L13-L15).

**Comment by Spone** [comment]
Thanks @markets! I emailed you for the keys. I updated my branch. Do I need to delete all cassettes that have been created in my PR?

**Comment by markets** [comment]
Sorry, I'm not really a VCR hardcore user 😅... I'm just using it here because the project was implemented this way when I started contributing. I think new cassettes are created when you add a new spec hitting a new URL, but to be sure, you can delete the new ones and run the specs again (if they appear again, this is probably the expected behavior).

**Comment by Spone** [comment]
I'm hitting `429 Too Many Requests` responses when running the tests. I'll wait for a bit and retry.

**Comment by Spone** [comment]
> Sorry, I'm not really a VCR hardcore user

Me neither, and I always get a bit confused with the default behavior...

Okay, I'm getting there, but I still have an odd behavior:

When running with the scraper, I get the following stats:

```
{"plays" => nil, "likes" => nil, "comments" => nil}
```

But when running with the API:

```
{"plays" => nil}
```

Is there a way to expect different things depending on the service used? Or should I aim at having the same output?

**Comment by markets** [comment]
Yes! Both implementations are a bit different, since info is not available in both versions:

**Scraper:**
https://github.com/thibaudgg/video_info/blob/2a94d69c978b2c19257c9729278adaa901901f95/lib/video_info/providers/vimeo_scraper.rb#L122

**Api:**
https://github.com/thibaudgg/video_info/blob/2a94d69c978b2c19257c9729278adaa901901f95/lib/video_info/providers/vimeo_api.rb#L72

In the specs, you can use the `api_key` var to check what version is running:

https://github.com/thibaudgg/video_info/blob/2a94d69c978b2c19257c9729278adaa901901f95/spec/lib/video_info/providers/vimeo_spec.rb#L1

Something like this 👇🏼 is probably enough:

```
if api_key
  ...
else
  ...
end  
```

**Comment by Spone** [comment]
Thanks for your help! I thing it's ready for review :)

**Review by markets — APPROVED** [review]
Ah right! I think this is due to another problem we should improve some day. The point is that the secret ENV vars in our CI are not shared with non-admins contributors (IIRC this is the default GH Actions behaviour). 

But the changes seems fine to me, so lets merge it and see how it goes in master.

Thanks!!

**Pull request merged**
