### PR TITLE
Added #author_url to Vimeo

### PR DESCRIPTION
**Pull request by vheuken**
I implemented `#author_url` in both VimeoAPI and VimeoScraper. I also updated the README. Ran Rubocop on lib/ and everything is clean. There will likely be Hound-CI warnings involving the specs, but those will be dealt with when we finish #122.

### CODE REVIEW

**Comment by thibaudgg** [comment]
Specs are failing but :+1:

**Comment by vheuken** [comment]
Let me rebase it with master now that I have fixtures in, then we'll see what's up.

**Comment by vheuken** [comment]
Specs pass all around!

**Comment by thibaudgg** [comment]
:+1:

**Pull request merged**
