### PR TITLE
Update vkontakte provider

### PR DESCRIPTION
**Pull request by drakmail**
Updated #52 pull request (rewrite code to get vkontakte video info, small fixes)

### CODE REVIEW

**Comment by drakmail** [comment]
Yey, it is finally working now :smile: 

PS. Travis failed on DailyMotion tests, which raises HTTP 500 error exception.

**Comment by drakmail** [comment]
Travis failed on dailymotion and whistie tests specs :confused:

**Comment by drakmail** [comment]
Seems that it is ready to merge (checked it on 191 vkontakte videos links)

**Comment by thibaudgg** [comment]
@drakmail awesome thanks, 2.4.1 released!

**Pull request merged**
