### PR TITLE
Custom exceptions

### PR DESCRIPTION
**Pull request by 0mega**
Implements custom VideoInfo HTTP exception to be thrown when http errors are caught during download of video details

### CODE REVIEW

**Comment by vheuken** [comment]
Thanks for the pull request. I think to get rid of some of the code duplication, we should change it to something like this:

```ruby
class Provider
...
  def _set_data_from_api(api_url = _api_url)
    begin
      _set_data_from_api_impl # defined for each individual provider (Youtube, YoutubeScraper, Vimeo, etc)
    rescue OpenURI::HTTPError, *NetHttpTimeoutErrors.all
      raise VideoInfo::HttpError.new "unexpected network error while fetching information about the video"
    end
  end
end
```

**Comment by 0mega** [comment]
@vheuken sure, it was a bit late yesterday, just wasn't thinking straight. Check if it looks ok plz.

**Comment by vheuken** [comment]
Looks good. Just a few things:

* I think `_set_data_from_api_impl(api_url = _api_url)` should be changed to just `_set_data_from_api_impl(api_url)`
*  Change `_set_data_from_api` to `_set_data_from_api_impl` for all other providers
* Fix the `Redundant begin block detected.` HoundCI warning (the other ones seem like they're fine to not fix)

Once you handle those it should be ready to merge!

**Comment by 0mega** [comment]
The default argument assignment was a mistake, wasn't supposed to commit it =|.

> Change _set_data_from_api to `_set_data_from_api_impl` for all other providers

Don't know if I understand what you mean by that.
In current implementation the base Provider class has `_set_data_from_api` and a default `set_data_from_api_impl`. The only classes with specific implementation of `_set_data_from_api_impl` are `YoutubeScraper`and `Vkontakte`. All the other providers use the default `set_data_from_api_impl`.
Please tell me what I'm missing

Thanks

**Comment by vheuken** [comment]
Oh, sorry. You're correct. Thanks for the help!

**Comment by 0mega** [comment]
Cool =)

**Pull request merged**
