### PR TITLE
Author Fields to Video Info

### PR DESCRIPTION
**Pull request by robguilfoyle**
## What is this?

This PR is adding in methods for fetching author information. Specifically these three fields:

 - Author Thumbnail
 - Author Name
 - Author Domain

### CODE REVIEW

**Comment by thibaudgg** [comment]
@robguilfoyle thanks for the PR, I'll have a look at it once #79 has been merged!

**Comment by robguilfoyle** [comment]
Thibaud, it actually needs some work on the other services, so for the time
being you can ignore it.

On Sun, Jul 19, 2015 at 2:09 PM, Thibaud Guillaume-Gentil <
notifications@github.com> wrote:

> @robguilfoyle <https://github.com/robguilfoyle> thanks for the PR, I'll
> have a look at it once #79
> <https://github.com/thibaudgg/video_info/pull/79> has been merged!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thibaudgg/video_info/pull/83#issuecomment-122689458>.
>



-- 
*Rob C. Guilfoyle*
m: 502.445.3616

**Comment by thibaudgg** [comment]
Master should be back to green now, could you rebase please? Thanks!

**Comment by vheuken** [comment]
@robguilfoyle Are you still planning on completing this?

**Comment by robguilfoyle** [comment]
I am, I just have not had time.

**Comment by vheuken** [comment]
No rush :+1:

**Comment by vheuken** [comment]
@robguilfoyle Are you still interested in finishing this?

**Comment by vheuken** [comment]
I tried to do a rebase of this, but I quickly realized it would be far too much of a hassle (could be because my git skills aren't up to the task). What I'll probably end up going is going through and picking out the code myself.

**Comment by robguilfoyle** [comment]
Hi Vincent,

I’m sorry it took me so long to respond to this. I just don’t have the time to follow back up on this at the moment. I believe the majority of the tests were passing where I left off, but I believe you guys may have added new video services not covered in these methods.

Rob Guilfoyle

— Sent from
https://polymail.io/

On Mon, Mar 07, 2016 at 3:22 PM Vincent Heuken

<
mailto:Vincent Heuken <notifications@github.com>
> wrote:

I tried to do a rebase of this, but I quickly realized it would be far too much of a hassle (could be because my git skills aren't up to the task). What I'll probably end up going is going through and picking out the code myself.

**Comment by vheuken** [comment]
I'm closing this and have made an issue for it in #119. @robguilfoyle If you would like to continue, feel free to reopen the pull request!

**Pull request closed without merging**
