### PR TITLE
Vkontakte author info

### PR DESCRIPTION
**Pull request by vheuken**
This PR is *NOT* complete. I have only implemented `#author` and `#author_thumbnail`.

I am posting this now because I need some help with `#author_url`. I'm not totally sure what an author's URL is expected to be on Vkontakte. Maybe @drakmail knows?

(Also, nice regex skills whoever wrote this initially. I'm a weenie and I just used `String::split`)

~~Also, heads up. One spec is expected to fail. It is unrelated to this PR. It is because of issue 125~~ 

#125 is fixed and I rebase, so this should be green. Just waiting on some help with the `#author_url` part.

### CODE REVIEW

**Comment by vheuken** [comment]
Never mind. I was a bit confused by the UI. I got `#author_url` implemented.

**Comment by vheuken** [comment]
Merging this!

**Comment by thibaudgg** [comment]
:+1:

**Comment by drakmail** [comment]
Hm, seems that `author_url` is really a link to all videos uploaded by author. Link to author profile is located in this lines:

```html
<div class="fl_l people_cell">
  <a class="ava" href="/lyanoi.kirill" onclick="return nav.go(this, event, {cl_id: 0})">
    <img width="50" height="50" src="https://pp.vk.me/c623824/v623824699/55574/evmtX1Spupk.jpg"/>
  </a>
  <div class="name_field">
    <a href="/lyanoi.kirill">
      Кирилл<br />
      <small></small>
    </a>
  </div>
</div>
```

Anyway, I'll soon fix it and several other small issues.

**Comment by vheuken** [comment]
@drakmail Thanks for the heads up. I'll open up an issue for this.

**Pull request merged**
