### PR TITLE
thumbnails for videos that are unavailable

### PR DESCRIPTION
**Pull request by elfassy**
previously this would crash as noted in issue #66

### CODE REVIEW

**Comment by elfassy** [comment]
There's some failing `YoutubePlaylist` that I didn't look at, but that should probably be a separate pull request

**Comment by thibaudgg** [comment]
Looks good, @vheuken is it fine for you?

**Comment by vheuken** [comment]
Yeah, looks good to me!

**Comment by thibaudgg** [comment]
:+1:

**Pull request merged**
