### PR TITLE
Added specs for author-info for Youtube Playlists

### LINKED ISSUE #119: Add author fields to services which currently don't have them implemented
This has been partially done in PR #83, but it isn't complete and a rebase would be a big hassle.

The three fields in question:
* Author Thumbnail
* Author Name
* Author Domain

### PR DESCRIPTION
**Pull request by vheuken**
Looks like with the API it just works thanks to Youtube sharing the same API interface between playlists and videos.

Just gotta handle it on the scraper and we can close #119 !

### CODE REVIEW

**Comment by vheuken** [comment]
Alright, this is done. Heads up, there are some *very* slight differences between the scraper and API in this case

```
YoutubePlaylistScraper#author_url => "https://www.youtube.com/user/YouTubeHelp"
YoutubePlaylistAPI#author_url     => "https://www.youtube.com/channel/UCMDQxm7cUx3yXkfeHa5zJIQ"

YoutubePlaylistAPI#author_thumbnail     => "https://yt3.ggpht.com/-ni_VaN38-AE/AAAAAAAAAAI/AAAAAAAAAAA/bJCTTfihBl0/s88-c-k-no/photo.jpg"
YoutubePlaylistScraper#author_thumbnail => "https://yt3.ggpht.com/-ni_VaN38-AE/AAAAAAAAAAI/AAAAAAAAAAA/bJCTTfihBl0/s100-c-k-no/photo.jpg"
```

**Comment by vheuken** [comment]
I'll clarify it to the documentation and add in some examples in a few hours, then this can be merged!

@thibaudgg Should we handle the other meta issues before the next release or should we release it now that we have the features in?

**Comment by thibaudgg** [comment]
> @thibaudgg Should we handle the other meta issues before the next release or should we release it now that we have the features in?

I think it fine to wait a little bit more, people can still use master if they really want it, that's the main reason to always have all specs green on master and using PR for all new features.

**Comment by vheuken** [comment]
Cool, no problem.

**Pull request merged**
