### PR TITLE
Facebook support 

### PR DESCRIPTION
**Pull request by vheuken**
This PR is still in progress. So far I have everything for one video except `#embed_url` and `#embed_code`. Also `#title` currently returns `nil`. I have never seen a Facebook video with a "title" so perhaps this will always return `nil`, but I'm not sure yet.

Once I get those in I'm going to add a variety of URL types to the spec.

Just a note, we need to make two API requests: one for the video info, one for the author info. I don't think there is any way around that.

Also, Rubinous fails because of URI encoding or something. When I explicitly encode the URI in provider.rb, it fixes Facebook and breaks the rest on regular Ruby. I'll investigate this in a bit.

I also made it so that `#freeze` is called on the `data` object when it is created. Didn't break anything, and having it immutable is probably a good idea.

### CODE REVIEW

**Comment by vheuken** [comment]
Fixed the Rubinous bug by just encoding the FB URIs in `_set_data_from_api_impl`.

**Comment by vheuken** [comment]
I'm getting a 400 Bad Request with this video: https://www.facebook.com/lllDavidACMlll/videos/10205379584751731

I'm extracting the ID from the URL just like I did with a video from a page, so I'm thinking maybe videos from profiles don't put a "video id" in the URL like pages do.....but I'm not sure what else they'd put in. I'll investigate.

**Comment by vheuken** [comment]
Looks like we might only be able to obtain info from Facebook pages unless you generate a "user access token" (which is generally obtained from the user "logging in"). With that knowledge, it is still doable, though actually testing it (since "user access tokens" are temporary) seems problematic. I'll let you know if I get more info.

**Comment by vheuken** [comment]
@thibaudgg I had a very brief conversation with an employee of Facebook, who confirmed that we need a "user access token" to access user videos. The thing is, I don't see any way we can actually test this.

I think we have two options:
1) Just do info for videos on Facebook pages
2) Allow users the option to enter an actual access token, and we only test that the access token is the preferred way to handle things and then just trust that the FB API works. We can also test that it falls back to `{app_id}|{app_secret}` if they are provided.

I'm leaning towards option #2.

**Comment by thibaudgg** [comment]
I would maybe remove the `{app_id}|{app_secret}` way for now and only allow the use of a proper `access_token` I don't think this the role of this gem to authorize on Facebook API.

Regarding testing, I would recommend to setup a dummy Facebook account that we can use to automate test, maybe [Koala Test Users feature](https://github.com/arsduo/koala#test-users) could help here.

**Comment by vheuken** [comment]
`{app_id}|{app_secret}` is a perfectly valid access token, though. It just only allows the gem to get public videos from Facebook pages.

>Regarding testing, I would recommend to setup a dummy Facebook account that we can use to automate test, maybe Koala Test Users feature could help here.

Sure, I can try that.

**Comment by thibaudgg** [comment]
`{app_id}|{app_secret}` is not a valid access token, it just credentials that allow you to get an access_token, so maybe have just the access token settings would be enough and how to get that access token could kept out of this gem.

**Comment by vheuken** [comment]
Well, you're right that it isn't an access token, but it _can_ be used as an access token, so I think we need to test it regardless (which I am now doing by just passing in in as `VideoInfo.provider_api_keys = { facebook_access_token: "#{app_id}|#{app_secret}" }`.
 
"There is another method to make calls to the Graph API that doesn't require using a generated app access token. You can just pass your app id and app secret as the access_token parameter when you make a call:
`https://graph.facebook.com/endpoint?key=value&amp;access_token=app_id|app_secret`"

See: https://developers.facebook.com/docs/facebook-login/access-tokens


But I agree that we should be testing other access tokens.

**Comment by vheuken** [comment]
Something I need to look into: https://developers.facebook.com/docs/apps/test-users

**Comment by vheuken** [comment]
I've made some test users for this app. I should be able to obtain test access tokens for them with the interface documented here: https://developers.facebook.com/docs/graph-api/reference/v2.5/app/accounts/test-users

**Comment by vheuken** [comment]
Oh, actually it looks like I can get pregenerated access tokens directly from the dashboard. That is very handy.

**Comment by vheuken** [comment]
Interesting...when using an access token from a test user, we get some odd results:

```
  1) VideoInfo::Providers::Facebook with public video from page #thumbnail should eq "https://scontent.xx.fbcdn.net/hvthumb-xpa1/v/t15.0-10/p160x160/12720103_1071391039550257_1997979656_n.jpg?oh=c29fe72d1d3a5be4e81071a0cd877a9a&oe=57528694"
     Failure/Error: it { is_expected.to eq thumbnail_url }

       expected: "https://scontent.xx.fbcdn.net/hvthumb-xpa1/v/t15.0-10/p160x160/12720103_1071391039550257_1997979656_n.jpg?oh=c29fe72d1d3a5be4e81071a0cd877a9a&oe=57528694"
            got: "https://scontent.xx.fbcdn.net/hvthumb-xpa1/v/t15.0-10/p160x160/12720103_1071391039550257_1997979656_n.jpg?oh=4391be67596fae96a84a68e27dcada79&oe=577A1394"
```

Both URLs point to the same image. I'm guessing that the URL arguments differ depending on the access token (probably to verify that the user has permission), so we should just test that it matches with the arguments stripped off.

**Comment by vheuken** [comment]
Closing this.

**Pull request closed without merging**
