### PR TITLE
Youtube Scraper

### PR DESCRIPTION
**Pull request by vheuken**
This is pretty much done, except for a few things:
* ~~THE INEVITABLE FLOOD OF HOUNDCI VIOLATIONS WOOO~~ Fewer than I expected
* ~~I should clean it up a bit. `#date`, `#description`, and a few other functions can have the bulk moved to a single helper function.~~ 
* ~~I apparently broke some YoutubePlaylist stuff in the process~~ ~~Most is fixed. Just need to get `#keywords` working on the API.~~ Done
* ~~Update documentation since an API key isn't required for most things anymore~~
  * ~~Note that the scraper only includes the date posted. API is required to get exact time.~~ DONE
* ~~I have a question about the spec. For `#keywords`, I'm getting this failed spec:~~

```ruby
  1) VideoInfo::Providers::Youtube with video mZqGqE0D0n4 #keywords should be nil
     Failure/Error: it { is_expected.to be_nil }
       expected: nil
            got: "cherry, bloom, king, of, the, knife, guitar, drum, clip, rock, alternative, tremplin, Paris-Forum"
     # ./spec/lib/video_info/providers/youtube_spec.rb:167:in `block (4 levels) in <top (required)>'
```

~~I assume the spec is wrong, but it passes with the API. The API code is probably doing something wrong. I'll have a better look in a day or two when I finish this. Opened this so I could document what I have to do next~~ Fixed the spec.

### CODE REVIEW

**Comment by vheuken** [comment]
I should also replace open-uri with Net::HTTP. I'm getting an open-uri error when I integrate it into my project and don't feel comfortable with `open_uri_redirections` now.

**Comment by thibaudgg** [comment]
Going back to Net::HTTP seems like a good idea! :+1:

**Comment by vheuken** [comment]
Wow, it looks like you can only get tags/keywords through the API if you authenticate as the user who owns the video. I guess I'll have it so that the API will scrape for this info.

**Comment by thibaudgg** [comment]
:+1:

**Comment by vheuken** [comment]
Keywords stuff is done. Just gotta fix the stuff that broke in YoutubePlaylist.

**Comment by vheuken** [comment]
I'm down to three failing specs. Unfortunately it's late and I'm going to have to save the final three specs + cleanup for tomorrow.

Getting close, though.

**Comment by thibaudgg** [comment]
@vheuken :+1: have a good night, thanks!

**Comment by vheuken** [comment]
Now down to one (plus a Vkontakte one that is unrelated). 

According to the API documentation, we should be getting the tags/keywords for the YoutubePlaylist with our API request.....but we're not. It's not giving us an empty list, it's just not returning giving a "tags" property at all. They definately exist though, since I am getting them through the scraper. Odd.

After that, just cleanup.

**Comment by robguilfoyle** [comment]
@vheuken do you expect to have this ready in the next few days?

**Comment by vheuken** [comment]
@robguilfoyle Yes. I'm going to be working on it more tonight.

**Comment by vheuken** [comment]
I removed all of the duplicate code in YoutubeScraper. Now all that is left is that spec and whatever houndci violations I made.

**Comment by thibaudgg** [comment]
@vheuken I'll be out in Vacation for two weeks starting tomorrow, so I'll most likely merge and deploy a new version when I'm back.

**Comment by vheuken** [comment]
@thibaudgg No problem. I'll _definitely_ be finished by then.

**Comment by thibaudgg** [comment]
@vheuken done?

**Comment by vheuken** [comment]
Unfortunately I still haven't had time. Still just one thing failing. I'll handle it either tonight or sometime tomorrow. Sorry for the delay.

**Comment by thibaudgg** [comment]
@vheuken no problem, take your time!

PS: Once we merged that PR, what would you think about joining me as a maintainer of VideoInfo?

**Comment by vheuken** [comment]
It looks like there is no way to check through the API if a video is no longer available on Youtube due to a copyright claim. It just treats it like a normal video and gets the info.

I'm not totally sure what the best way to proceed is. One option is to just allow `available?` to return true through the API, since it _does_ get all the necessary info. What do you think?

>PS: Once we merged that PR, what would you think about joining me as a maintainer of VideoInfo?

Sure, I'd be happy to do that.

**Comment by thibaudgg** [comment]
I'm fine with always returning true when using `available?` though the API. :+1:

**Comment by vheuken** [comment]
Right now all the Youtube bugs are fixed. There's still a bug in YoutubePlaylist API where it doesn't get keywords. I'll have to see if that is a regression or if it never worked.

**Comment by thibaudgg** [comment]
Awesome, looking forward to merge this PR!

**Comment by vheuken** [comment]
This is odd. I checked, and back before I did the stuff for the API, the spec said `#keywords` were expected to be nil. When I implemented the YoutubePlaylist scraper, I saw that there was a section for keywords in the HTML and added that to the spec. The v3 API doesn't seem to give keywords for playlists.

So....couple options here:
A) Go back to how 2.4.1 worked and just have `#keywords` in YoutubePlaylist return nil
B) Let YoutubePlaylist continue returning the keywords it finds in the HTML, and have the API return nil
C) Have the API continue to try to find the keywords and just stub out the spec

**Comment by vheuken** [comment]
I'm leaning towards option A. It prevents breakage if someone switches from the scraper to the API and is consistent with earlier versions of the video_info.

**Comment by thibaudgg** [comment]
Let's go with A. and maybe open a issue about it so we can fix it later. :+1:

**Comment by vheuken** [comment]
Now the only spec failing is `Vkontakte#available?`, which is unrelated.

**Comment by vheuken** [comment]
Oh wait, jruby is failing like crazy, but that's all Vkontakte stuff. I can give that a look soon.

**Comment by thibaudgg** [comment]
:+1: Thanks a lot!

**Comment by AknEp** [comment]
:+1:

**Pull request merged**
